In [1]:
# Numpy is a python library for performing scientific calculations. Pandas is built on top of Numpy

In [18]:
#creating a numpy array or NDarray. A numpy array is similar to list but has a fixed size and same data type

import numpy as np

new_array = np.array([1,22,57,2323,12,3223,23234,24412121])


print("The type is :",type(new_array)) #prints the type of the array
print("The data type is :",new_array.dtype) #prints the datatype of the array
new_array.size #Gives the size of the array


The type is : <class 'numpy.ndarray'>
The data type is : int32


8

In [22]:
# updating the array, scliing the array

new_array[0] = 100
print(new_array[0:3])

[100  22  57]


In [27]:
# Working with 2D arrays
list = [[12,13,14],[1,2,3],[22,23,24]]
Twodarray = np.array(list)
Twodarray

array([[12, 13, 14],
       [ 1,  2,  3],
       [22, 23, 24]])

In [30]:
print(Twodarray.ndim) # gives the dimension of the array
print(Twodarray.shape) #gives the shape of the array

2
(3, 3)


In [37]:
#Accessing the 2-D array and slicing

print(Twodarray[0][2])
print(Twodarray[0][1])

#sclicing
print(Twodarray[0,:2])
print(Twodarray[0:3,2])

14
13
[12 13]
[14  3 24]
